#!/bin/env bash
# A script to open a interpreter language in the terminal

option=$(printf "\\ue777 Haskell\\n\\uf81d Javascript\\n\\ue620 Lua\\n\
\\uf820 Python 2\\n\\uf81f Python 3\\n\\ufcd2 R" | fzf --prompt="language" \
| cut -f1 -d' ' --complement)

case $option in
    "Haskell")
        ghci
        ;;
    "Javascript")
        node
        ;;
    "Lua")
        lua
        ;;
    "Python 3")
        python3
        ;;
    "Python 2")
        python2
        ;;
    "R")
        R -q --no-save
        ;;
    *)
        ;;
esac
