#!/bin/env sh
# If run by itself sets the wallpaper; if given a file set that as the new
# wallpaper. If given a directory choose a random file in it.

bgloc="${XDG_CACHE_HOME:-$HOME/.cache/}/bg.png"

[ -f "$1" ] && ln -sf "$(readlink -f "$1")" "$bgloc" && notify-send -i \
    "$bgloc" "Changing wallpaper..." 
[ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" \
    -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" \
    && notify-send -i "$bgloc" "Random wallpaper chosen."

xwallpaper --zoom "$bgloc"
